imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            root_path: 
                - "mvc/me/report"
            environment:
                php:
                    version: 8.3.3
                node: "16"
            commands:
                - node -v
                - npm install
                - npm run build

        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    # - phpcs-run # Not used, missing config file

    tests:
        override:
            - command: "composer phpunit"
              coverage:
                  file: "docs/coverage.clover"
                  format: "php-clover"

